# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: Apache-2.0
---
name: 'launch-specified-action'
description: >-
  GitHub docker container Action that launches another specified image. The
  specified docker container will be launched with:

  > docker run {{ inputs.docker_args }} {{ inputs.image }} {{ inputs.image_args }}
author: 'vicamo'

inputs:
  docker_args:
    description: >-
      Arguments to be passed to the `docker run` command that launches the
      specified image.
    default: ''
  include_env_match:
    description: >-
      Regular expression used to match environment variable names to be passed
      to the container to be launched.
    default: ''
  image:
    description: The docker image to be launched.
    required: true
  image_args:
    description: Arguments to be passed to the launched docker image.
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '/start.sh'
