# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: Apache-2.0
---
name: 'launch-specified-action'
description: >-
  GitHub docker container Action that launches another specified image. The
  specified docker container will be launched with:

  > docker run {{ inputs.docker_args }} {{ inputs.image }} {{ inputs.image_cmds }}
author: 'vicamo'

inputs:
  image:
    description: Target docker image to launch.
    required: true
  include_env_match:
    description: >-
      Regular expression to match additional environment variables to pass into
      the launched container.
    default: ''
  docker_args:
    description: Additional arguments to launch the docker image.
    default: ''
  image_cmds:
    description: Additional command arguments for the docker image.
    default: ''

runs:
  using: 'docker'
  image: 'ghcr.io/hustle-ci/launcher:latest'
  args:
    - '/start.sh'
    - '--'
    - ${{ inputs.image }}
